export const shippingFields = [{
        required: true,
        id: "address",
        name: "address",
        label: "Direccion",
        fullWidth: true,
        autoComplete: "Direccion",
    },
    {
        required: false,
        id: "addressObs",
        name: "addressObs",
        label: "Entre calles",
        fullWidth: true,
        autoComplete: "Aclaracion",
    },
    {
        required: true,
        id: "city",
        name: "city",
        label: "Ciudad",
        fullWidth: true,
        autoComplete: "Ciudad",
    },
    {
        required: true,
        id: "postalCode",
        name: "postalCode",
        label: "Codigo Postal",
        fullWidth: true,
        autoComplete: "Codigo Postal",
    },
    {
        required: true,
        id: "locality",
        name: "locality",
        label: "Localidad",
        fullWidth: true,
        autoComplete: "Localidad",
    },
]